### ISSUE TITLE
provisioning issues encountered

### ISSUE THREAD

**Issue by joylatten** [project-machine/trust#48]
1. build-livecd-rfs requires $ROOTFS_VERSION
    Perhaps we can pass in as an argument or just export it.
2.  trust/live/provision-stacker.yaml gets an old mosctl that was not built using the latest trust changes to get pcr7 from /pcr7.bin rather than from tpm2_pcrread when provisioning. This caused a pcr7 that was not in signdata.
3. actually all the trust/live/*-stacker.yaml have above issue.

**Comment by hallyn** [comment]
> trust/live/provision-stacker.yaml gets an old mosctl that was not built using the latest trust changes to get pcr7 from /pcr7.bin rather than from tpm2_pcrread when provisioning. This caused a pcr7 that was not in signdata.

So we need at least 0.0.10, should probably use 0.0.11.

**Comment by joylatten** [comment]
3. Another issue I encountered was the requirement of a disk being at least 120G. The code errors out if it is not at least that much. I did not realize this and just did 40G.  I wish there was a way to make that easily known. Maybe the error message could pointedly say, your disk size is too small, need at least 120G. Or maybe I could modify README and put there.
