### ISSUE TITLE
keyctl doesn't have UserKeyring function (but has UserSessionKeyring).

### ISSUE THREAD

**Issue by ashwing123** [project-machine/trust#50]
In `trust/tpm2.go` the user's keyring is generated via `keyring, err := keyctl.UserKeyring()` in lines 694 and 766. However, keyctl has function `UserSessionKeyring` not `UserKeyring`. For some reason this is only an issue I'm seeing on `aarch64`, as trust still builds on `x86_64` platform.

**Comment by hallyn** [comment]
It was introduced in https://github.com/jsipprell/keyctl/pull/13 .
